hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S-%f}

defaults:
  - dataset: mnist
  - optimizer: sgd
  - _self_

seed: 42
num_steps: 100000
train_size: 1000
batch_size: 100
init_scale: 8.0
depth: 3
hidden_size: 200
calc_nhsic: true
calc_mi_estimation: true

wandb:
  project: collapse_dynamics
  entity: keitaroskmt
  job_type: train_mnist
