hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S-%f}

defaults:
  - dataset: mnist
  - optimizer: sgd
  - model: toy_mlp
  - _self_

seed: 42
num_steps: 100000
train_size: 1000
batch_size: 100
init_scale: 8.0
calc_nhsic: false
nhsic_num_iter: 3
calc_mi_estimation: false
calc_mi_estimation_compression: false
save_model: false

wandb:
  project: collapse_dynamics
  entity: keitaroskmt
  job_type: change_weight_decay
